services:
  vertd:
    build: .
    environment:
      - PORT=${PORT:-24153}
    ports:
      - "${PORT:-24153}:${PORT:-24153}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
