name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: vert-mac
            friendly-name: mac-arm64
            target: aarch64-apple-darwin
            format: ""
          # TODO: set up more self-hosted runners
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --target ${{ matrix.target }} --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: target/${{ matrix.target }}/release/vertd${{ matrix.format }}
          name: vertd-${{ matrix.friendly-name }}${{ matrix.format }}

  release:
    name: Publish release
    needs: build # wait for all builds to finish
    runs-on: vert-mac # TODO: run on vert-linux instead for slightly faster releases (thanks kvm!)
    permissions:
      contents: write # necessary for releases?
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ github.sha }}
          name: "Nightly build #${{ github.run_number }}"
          draft: false
          prerelease: false
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
