name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            rust: stable
          - os: macos-latest
            target: x86_64-apple-darwin
            rust: stable
          - os: macos-latest
            target: aarch64-apple-darwin
            rust: stable

    steps:
      - uses: actions/checkout@v4

      - name: install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: install dependencies (windows)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y mingw-w64

      - name: build
        run: cargo build --release --target ${{ matrix.target }}
